# Generated by Django 4.2.10 on 2024-03-15 07:15

from django.db import migrations, models
import django.db.models.deletion
import ledger.models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=50)),
                ('user_bio', models.TextField(max_length=756, validators=[ledger.models.minimumBio])),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ledger.profile'),
        ),
    ]
